import 'package:path/path.dart' as p;
import 'package:stardust/src/config/config.dart';
import 'package:stardust/src/generator/version_planner.dart';
import 'package:test/test.dart';

void main() {
  group('planVersionBuilds', () {
    const config = StardustConfig(
      name: 'T',
      content: ContentConfig(dir: 'docs'),
      versions: VersionsConfig(
        enabled: true,
        current: '2.0',
        list: [
          VersionEntry(version: '2.0', path: '/', label: 'v2'),
          VersionEntry(version: '1.0', path: '/v1/', source: DirSource('versions/1.0')),
        ],
      ),
    );

    test('returns empty when no versions are configured', () {
      expect(planVersionBuilds(const StardustConfig(name: 'T'), 'dist'), isEmpty);
    });

    test('routes the root version to the base output with no prefix', () {
      final root = planVersionBuilds(config, 'dist').first;

      expect(root.entry.version, '2.0');
      expect(root.source, const DirSource('docs'), reason: 'defaults to the live content dir');
      expect(root.outputDir, 'dist');
      expect(root.versionBasePath, isNull);
      expect(root.noindex, isFalse, reason: 'the current version stays indexable');
    });

    test('routes an older version into its path segment with noindex', () {
      final old = planVersionBuilds(config, 'dist')[1];

      expect(old.source, const DirSource('versions/1.0'));
      expect(old.outputDir, p.join('dist', 'v1'));
      expect(old.versionBasePath, '/v1');
      expect(old.noindex, isTrue);
    });

    test('carries a git source through to the build task', () {
      const gitConfig = StardustConfig(
        name: 'T',
        versions: VersionsConfig(
          enabled: true,
          current: '2.0',
          list: [
            VersionEntry(version: '2.0', path: '/'),
            VersionEntry(version: '1.0', path: '/v1/', source: GitSource('v1.0.0')),
          ],
        ),
      );

      expect(planVersionBuilds(gitConfig, 'dist')[1].source, const GitSource('v1.0.0'));
    });

    test('nests version prefixes under an existing site basePath', () {
      const nested = StardustConfig(
        name: 'T',
        build: BuildConfig(basePath: '/stardust'),
        versions: VersionsConfig(
          enabled: true,
          current: '2.0',
          list: [
            VersionEntry(version: '2.0', path: '/'),
            VersionEntry(version: '1.0', path: '/v1/'),
          ],
        ),
      );

      final tasks = planVersionBuilds(nested, 'dist');

      expect(tasks[0].versionBasePath, '/stardust');
      expect(tasks[1].versionBasePath, '/stardust/v1');
    });
  });

  group('sidebarForVersion', () {
    const sidebar = [
      SidebarGroup(group: 'Guides', pages: [SidebarPage(slug: 'index'), SidebarPage(slug: 'newfeature')]),
      SidebarGroup(group: 'Gone', pages: [SidebarPage(slug: 'newfeature')]),
      SidebarGroup(group: 'Auto', autogenerate: AutogenerateConfig(dir: 'api')),
    ];

    test('returns the sidebar untouched when the version has no page index', () {
      expect(sidebarForVersion(sidebar, null), same(sidebar));
    });

    test('drops entries the version does not have and groups left empty', () {
      final result = sidebarForVersion(sidebar, {'/'});

      expect(result.map((g) => g.group), ['Guides', 'Auto']);
      expect(result.first.pages.map((p) => p.slug), ['index']);
    });

    test('keeps autogenerated groups regardless of the page index', () {
      expect(sidebarForVersion(sidebar, <String>{}).map((g) => g.group), ['Auto']);
    });

    test('preserves group presentation when filtering', () {
      const collapsed = [
        SidebarGroup(group: 'G', icon: 'book', collapsed: true, pages: [SidebarPage(slug: 'index')]),
      ];

      final group = sidebarForVersion(collapsed, {'/'}).single;

      expect(group.icon, 'book');
      expect(group.collapsed, isTrue);
    });
  });

  group('routeUnderPath', () {
    test('keeps a root path at the base with no prefix', () {
      expect(routeUnderPath('/', '', 'dist'), (outputDir: 'dist', basePath: null));
      expect(routeUnderPath('/', '/docs', 'dist'), (outputDir: 'dist', basePath: '/docs'));
    });

    test('nests a path segment under the base and output', () {
      expect(routeUnderPath('/es/', '', 'dist'), (outputDir: p.join('dist', 'es'), basePath: '/es'));
      expect(routeUnderPath('/v1/', '/docs', 'dist'), (outputDir: p.join('dist', 'v1'), basePath: '/docs/v1'));
    });
  });

  group('rootRedirectTarget', () {
    List<VersionBuildTask> tasksFor(String currentPath) => planVersionBuilds(
          StardustConfig(
            name: 'T',
            versions: VersionsConfig(
              enabled: true,
              current: '2.0',
              list: [
                VersionEntry(version: '2.0', path: currentPath),
                const VersionEntry(version: '1.0', path: '/v1/'),
              ],
            ),
          ),
          'dist',
        );

    test('is null when the current version builds at the root', () {
      expect(rootRedirectTarget(tasksFor('/'), 'dist', '2.0'), isNull);
    });

    test('points at the current version when it lives under a prefix', () {
      expect(rootRedirectTarget(tasksFor('/v2/'), 'dist', '2.0'), '/v2/');
    });
  });

  group('currentVersionSitemapUrl', () {
    StardustConfig configFor({String? url, String path = '/', bool sitemap = true}) => StardustConfig(
          name: 'T',
          url: url,
          build: BuildConfig(sitemap: SitemapConfig(enabled: sitemap)),
          versions: VersionsConfig(
            enabled: true,
            current: '2.0',
            list: [VersionEntry(version: '2.0', path: path)],
          ),
        );

    test('is null without a site url or with sitemaps disabled', () {
      expect(currentVersionSitemapUrl(configFor(url: null)), isNull);
      expect(currentVersionSitemapUrl(configFor(url: 'https://example.com', sitemap: false)), isNull);
    });

    test('targets the root sitemap when the current version is at the root', () {
      expect(currentVersionSitemapUrl(configFor(url: 'https://example.com')), 'https://example.com/sitemap.xml');
    });

    test('targets the prefixed sitemap when the current version is under a prefix', () {
      expect(
        currentVersionSitemapUrl(configFor(url: 'https://example.com', path: '/v2/')),
        'https://example.com/v2/sitemap.xml',
      );
    });
  });
}
