import 'dart:io';

import 'package:path/path.dart' as p;

import '../core/file_system.dart';

/// Marker written into every build output; its presence tells clean logic
/// that the directory was generated by Stardust and is safe to delete.
const outputGuardMarker = '.stardust-build';

const buildMarkerContent = 'This directory is generated by `stardust build`.\n'
    'Its presence allows `stardust build --clean` to delete the directory on the next build.\n';

/// The reason [outputDir] must never be deleted, or null when it is safe to clean.
Future<String?> unsafeCleanReason(FileSystem fileSystem, String outputDir) async {
  final resolved = p.canonicalize(outputDir);
  final cwd = p.canonicalize(Directory.current.path);

  if (p.equals(resolved, cwd) || p.isWithin(resolved, cwd)) {
    return 'it is the current directory or contains it';
  }
  final home = Platform.environment['HOME'] ?? Platform.environment['USERPROFILE'];
  if (home case final home? when p.equals(resolved, p.canonicalize(home))) {
    return 'it is your home directory';
  }
  if (await fileSystem.fileExists(p.join(outputDir, outputGuardMarker))) return null;
  if (await fileSystem.listDirectory(outputDir).isEmpty) return null;
  return 'it was not created by Stardust (no $outputGuardMarker marker) and is not empty';
}
